### ISSUE TITLE
代码格式

### ISSUE THREAD

**Issue by songyu-wang98** [gufeijun/blog#1]
一个小建议，就是上传代码的时候先格式化一下，这样其他人看起来可能会更方便些

**Comment by gufeijun** [comment]
我看了下，好像没有出现乱格式的代码诶，你能具体说说哪个文件有问题吗

**Comment by songyu-wang98** [comment]
> 我看了下，好像没有出现乱格式的代码诶，你能具体说说哪个文件有问题吗

抱歉，可能我表述有问题。

就是代码本身格式化一下再上传，类似 `gofmt` 指令执行过后或者 GoLand 按下 `command + option + L` 后的代码样式，会看起来更方便些。

在阅读你的代码的过程中，可能会增加/删除部分代码进行调试，这个时候如果进行了格式化代码的操作，`git diff` 就会展示出来大量的不同，导致阅读效果变差。

是非常棒的项目，个人感觉如果能把这点加上就更好了。

**Comment by gufeijun** [comment]
非常感谢指出，我看了下确实是有部分代码没格式化，下次得注意下。非常欢迎pr
